"""Adding Question table

Revision ID: 32298d9431c1
Revises: dcf675c72421
Create Date: 2024-10-03 11:58:45.700312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32298d9431c1'
down_revision = 'dcf675c72421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    # ### end Alembic commands ###
