"""Remove unique constraint on highscore

Revision ID: 360c5c128d64
Revises: 
Create Date: 2024-09-30 21:34:06.767926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360c5c128d64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_highscore', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint('uq_user_highscore', ['highscore'])

    # ### end Alembic commands ###
