"""ACTUALLY ADDING QUESTION TABLE I IMPORTED IT CORRECTLY

Revision ID: 3b07a0d5717e
Revises: 32298d9431c1
Create Date: 2024-10-03 12:01:31.762447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b07a0d5717e'
down_revision = '32298d9431c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('options', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    op.drop_table('question')
    # ### end Alembic commands ###
