"""fixing question table

Revision ID: dcf675c72421
Revises: 31fdb01f7785
Create Date: 2024-10-03 11:51:29.955160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf675c72421'
down_revision = '31fdb01f7785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('answer')
    op.drop_table('quiz')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    op.create_table('quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_quiz')
    )
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=500), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_answer_question_id_question'),
    sa.PrimaryKeyConstraint('id', name='pk_answer')
    )
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=500), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name='fk_question_quiz_id_quiz'),
    sa.PrimaryKeyConstraint('id', name='pk_question')
    )
    # ### end Alembic commands ###
